agents:
  - name: python-fullstack
    when:
      labels:
        - agent-task
    instructions: |
      Always create a new branch.
      Never commit directly to main.
      Use kebab-case based on the issue title.
      Open a pull request when done.
      Link the PR to the issue.
